Fix exception in isEnabled of CompareIndexWithHeadActionHandler
This fixes the following exception currently happening each time the
context menu of a Git-shared project is opened:

  java.lang.IllegalArgumentException: Empty path not permitted.

This happened in isStaged because resRelPath is "" when a project is at
the root of the repository.

Change-Id: Ie85d5f95b6c6d4b8154c220cfa1f7fd499a616ef
Signed-off-by: Robin Stocker <robin@nibor.org>